/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RechargeCheckoutRouteImport } from './routes/recharge.checkout'
import { Route as RechargePendingRouteImport } from './routes/recharge.pending'
import { Route as RechargeSuccessRouteImport } from './routes/recharge.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeCheckoutRoute = RechargeCheckoutRouteImport.update({
  id: '/recharge/checkout',
  path: '/recharge/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargePendingRoute = RechargePendingRouteImport.update({
  id: '/recharge/pending',
  path: '/recharge/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeSuccessRoute = RechargeSuccessRouteImport.update({
  id: '/recharge/success',
  path: '/recharge/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/offers': typeof OffersRoute
  '/operator': typeof OperatorRoute
  '/plans': typeof PlansRoute
  '/products': typeof ProductsRoute
  '/recharge/checkout': typeof RechargeCheckoutRoute
  '/recharge/pending': typeof RechargePendingRoute
  '/recharge/success': typeof RechargeSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/offers': typeof OffersRoute
  '/operator': typeof OperatorRoute
  '/plans': typeof PlansRoute
  '/products': typeof ProductsRoute
  '/recharge/checkout': typeof RechargeCheckoutRoute
  '/recharge/pending': typeof RechargePendingRoute
  '/recharge/success': typeof RechargeSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/offers': typeof OffersRoute
  '/operator': typeof OperatorRoute
  '/plans': typeof PlansRoute
  '/products': typeof ProductsRoute
  '/recharge/checkout': typeof RechargeCheckoutRoute
  '/recharge/pending': typeof RechargePendingRoute
  '/recharge/success': typeof RechargeSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/complaints'
    | '/dashboard'
    | '/history'
    | '/offers'
    | '/operator'
    | '/plans'
    | '/products'
    | '/recharge/checkout'
    | '/recharge/pending'
    | '/recharge/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/complaints'
    | '/dashboard'
    | '/history'
    | '/offers'
    | '/operator'
    | '/plans'
    | '/products'
    | '/recharge/checkout'
    | '/recharge/pending'
    | '/recharge/success'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/complaints'
    | '/dashboard'
    | '/history'
    | '/offers'
    | '/operator'
    | '/plans'
    | '/products'
    | '/recharge/checkout'
    | '/recharge/pending'
    | '/recharge/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComplaintsRoute: typeof ComplaintsRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  OffersRoute: typeof OffersRoute
  OperatorRoute: typeof OperatorRoute
  PlansRoute: typeof PlansRoute
  ProductsRoute: typeof ProductsRoute
  RechargeCheckoutRoute: typeof RechargeCheckoutRoute
  RechargePendingRoute: typeof RechargePendingRoute
  RechargeSuccessRoute: typeof RechargeSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge/checkout': {
      id: '/recharge/checkout'
      path: '/recharge/checkout'
      fullPath: '/recharge/checkout'
      preLoaderRoute: typeof RechargeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge/pending': {
      id: '/recharge/pending'
      path: '/recharge/pending'
      fullPath: '/recharge/pending'
      preLoaderRoute: typeof RechargePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge/success': {
      id: '/recharge/success'
      path: '/recharge/success'
      fullPath: '/recharge/success'
      preLoaderRoute: typeof RechargeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComplaintsRoute: ComplaintsRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  OffersRoute: OffersRoute,
  OperatorRoute: OperatorRoute,
  PlansRoute: PlansRoute,
  ProductsRoute: ProductsRoute,
  RechargeCheckoutRoute: RechargeCheckoutRoute,
  RechargePendingRoute: RechargePendingRoute,
  RechargeSuccessRoute: RechargeSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
