/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RechargeSuccessRouteImport } from './routes/recharge.success'
import { Route as RechargePendingRouteImport } from './routes/recharge.pending'
import { Route as RechargeCheckoutRouteImport } from './routes/recharge.checkout'

const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeSuccessRoute = RechargeSuccessRouteImport.update({
  id: '/recharge/success',
  path: '/recharge/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargePendingRoute = RechargePendingRouteImport.update({
  id: '/recharge/pending',
  path: '/recharge/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeCheckoutRoute = RechargeCheckoutRouteImport.update({
  id: '/recharge/checkout',
  path: '/recharge/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/offers': typeof OffersRoute
  '/plans': typeof PlansRoute
  '/recharge/checkout': typeof RechargeCheckoutRoute
  '/recharge/pending': typeof RechargePendingRoute
  '/recharge/success': typeof RechargeSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/offers': typeof OffersRoute
  '/plans': typeof PlansRoute
  '/recharge/checkout': typeof RechargeCheckoutRoute
  '/recharge/pending': typeof RechargePendingRoute
  '/recharge/success': typeof RechargeSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/offers': typeof OffersRoute
  '/plans': typeof PlansRoute
  '/recharge/checkout': typeof RechargeCheckoutRoute
  '/recharge/pending': typeof RechargePendingRoute
  '/recharge/success': typeof RechargeSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/offers'
    | '/plans'
    | '/recharge/checkout'
    | '/recharge/pending'
    | '/recharge/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/offers'
    | '/plans'
    | '/recharge/checkout'
    | '/recharge/pending'
    | '/recharge/success'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/offers'
    | '/plans'
    | '/recharge/checkout'
    | '/recharge/pending'
    | '/recharge/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  OffersRoute: typeof OffersRoute
  PlansRoute: typeof PlansRoute
  RechargeCheckoutRoute: typeof RechargeCheckoutRoute
  RechargePendingRoute: typeof RechargePendingRoute
  RechargeSuccessRoute: typeof RechargeSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge/success': {
      id: '/recharge/success'
      path: '/recharge/success'
      fullPath: '/recharge/success'
      preLoaderRoute: typeof RechargeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge/pending': {
      id: '/recharge/pending'
      path: '/recharge/pending'
      fullPath: '/recharge/pending'
      preLoaderRoute: typeof RechargePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge/checkout': {
      id: '/recharge/checkout'
      path: '/recharge/checkout'
      fullPath: '/recharge/checkout'
      preLoaderRoute: typeof RechargeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  OffersRoute: OffersRoute,
  PlansRoute: PlansRoute,
  RechargeCheckoutRoute: RechargeCheckoutRoute,
  RechargePendingRoute: RechargePendingRoute,
  RechargeSuccessRoute: RechargeSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
